import os
if os.path.isfile("path/to/config/file.json"):
    os.remove("path/to/config/file.json")

import os 
import glob
cookie_del = glob.glob("config/*cookie.json")
os.remove(cookie_del[0])


# Time delay
from datetime import datetime
from threading import Timer

x=datetime.today()
y=x.replace(day=x.day+1, hour=1, minute=0, second=0, microsecond=0)
delta_t=y-x

secs=delta_t.seconds+1

def hello_world():
    print ("hello world")
    #...

t = Timer(secs, hello_world)
t.start()
from instabot import Bot
bot = Bot()

bot.login(username="satak_sk",password="Write password for Skata")

bot.upload_photo("1.jpg",caption="Programing Memes(auto-generated by Skata[bot who manages this account])")
bot.upload_photo("2.jpg",caption="Programing Memes(auto-generated by Skata[bot who manages this account])")
bot.upload_photo("3.jpg",caption="Programing Memes(auto-generated by Skata[bot who manages this account])")
bot.upload_photo("4.jpg",caption="Programing Memes(auto-generated by Skata[bot who manages this account])")
bot.upload_photo("5.jpg",caption="Programing Memes(auto-generated by Skata[bot who manages this account])")

if os.path.exists("1.jpg.REMOVE_ME"):
  os.remove("1.jpg.REMOVE_ME")
  os.remove("2.jpg.REMOVE_ME")
  os.remove("3.jpg.REMOVE_ME")
  os.remove("4.jpg.REMOVE_ME")
  os.remove("5.jpg.REMOVE_ME")
else:
  os.remove("1.jpg.REMOVE_ME")
  os.remove("2.jpg.REMOVE_ME")
  os.remove("3.jpg.REMOVE_ME")
  os.remove("4.jpg.REMOVE_ME")
  os.remove("5.jpg.REMOVE_ME")